### ISSUE TITLE
webp image opens in .Devel but errors out on latest flathub

### ISSUE THREAD

**Issue by Channeira** [flathub/org.gnome.Loupe#17]
This webp image from a game shows the following error on the latest Flathub version of Loupe, but works perfectly fine on latest `.Devel`. This does not affect all webp images (example attached below).

![image](https://github.com/flathub/org.gnome.Loupe/assets/45535201/09d036cf-0a01-4f72-805d-3f3d106b96b4)

Example image (github doesn't allow attaching webp, so I zipped it once): [example.zip](https://github.com/flathub/org.gnome.Loupe/files/12279812/example.zip)

**Comment by sophie-h** [comment]
Thanks for your report!

This error has been fixed via https://github.com/image-rs/image/pull/1947. We are only waiting for a new release https://github.com/image-rs/image/pull/1973 to happen to get those fixes into Image Viewer.

If possible, please report future bugs in the official issue tracker.

**Comment by sophie-h** [comment]
Update that fixes this issue should be available in a few hours.

**Comment by Channeira** [comment]
Thank you very much Sophie! The image opens up nicely with the new update.

**Comment by Channeira** [comment]
Though I noticed just now that the Loupe process will not quit after closing the image. Weird, sometimes it does, other times it doesn't.

```
flatpak ps
Instance   PID  Application     Runtime
2743379067 8797 org.gnome.Loupe org.gnome.Platform
1834477822 8796 org.gnome.Loupe org.gnome.Platform
3016854829 8794 org.gnome.Loupe org.gnome.Platform
2115215195 8795 org.gnome.Loupe org.gnome.Platform
253893663  8793 org.gnome.Loupe org.gnome.Platform
```
