### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.gnome.Loupe#35]
The `host` permission is quite vast.  Why does it need access to the entire filesystem? As far as I'm aware, it can access any file through a portal. It doesn't need constant access to a user's system?

**Comment by nalsai** [comment]
From my understanding, it can only access the selected file(s) through a portal. 
When looking at images, one often wants to just select the first image and then be able to go through all images using the arrow keys.

**Comment by sophie-h** [comment]
Correct, it's also documented in the manifest

![image](https://github.com/flathub/org.gnome.Loupe/assets/3466497/10f211ad-4852-4646-bafa-6e13552f99ba)
