### ISSUE TITLE
Fullscreen mode by default and quit the app via ESC key

### ISSUE THREAD

**Issue by ralph303** [flathub/org.gnome.Loupe#56]
I have two questions / enhancement requests for Loupe:
- is it possible to always start Loupe in fullscreen mode by default when double clicking images in Nautilus?
- is it possible to add a function "exit Loupe by pressing the escape key"? This isn't possible right now, you can only leave fullscreen mode ny pressing escape.

These features are important for an efficient workflow and it would be really sad to be forced to switch image viewer just because of these two little enhancements.

**Comment by A6GibKm** [comment]
Hello, this is a repository for the flathub distribution of the app, not for the app itself. I would suggest joining the matrix channel (see the upstream repository of loupe which should have a link) and ask there.
