### ISSUE TITLE
can't browse folder in /usr

### ISSUE THREAD

**Issue by tenturestept** [flathub/org.gnome.Loupe#73]
this is on fedora 41.

if i open an image like `/usr/share/backgrounds/gnome/adwaita-d.jxl` from gnome files, it will view the image, but the options for navigating the folder are greyed out. even though there are other images in the folder. also the folder name on the right side is a random string instead of "gnome".

this bug doesn't occur with loupe installed from dnf

**Comment by A6GibKm** [comment]
The sandbox has its own version of `/usr,` this is to be expected and cannot be worked around. With sufficient fs permissions, you can access the host's `/usr` at `/run/host/usr` from within the sandbox.

**Comment by sophie-h** [comment]
For general questions, please use https://discourse.flathub.org/
